apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tattler.fullname" . }}-config
  labels: {{- include "tattler.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
