{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tattler.fullname" . }}-token
  labels: {{- include "tattler.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "discordToken or existingSecret must be set" .Values.discordToken | b64enc | quote }}
{{- end }}
